// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRjMQbeHWUOt1TQ3XsXjA4_k1j9HXo3Oc',
    appId: '1:765220729594:web:48ad032ce0ee09d1e64f43',
    messagingSenderId: '765220729594',
    projectId: 'gastos-aa516',
    authDomain: 'gastos-aa516.firebaseapp.com',
    storageBucket: 'gastos-aa516.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5n722oFqAcb8I1Rr-ui0QFnJDaB1rKhc',
    appId: '1:765220729594:android:1a61bac254e731a3e64f43',
    messagingSenderId: '765220729594',
    projectId: 'gastos-aa516',
    storageBucket: 'gastos-aa516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFG2GIh9N-_ZDWi_YbCqFlFYXmGjnzYsU',
    appId: '1:765220729594:ios:ab126841c24ba241e64f43',
    messagingSenderId: '765220729594',
    projectId: 'gastos-aa516',
    storageBucket: 'gastos-aa516.appspot.com',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFG2GIh9N-_ZDWi_YbCqFlFYXmGjnzYsU',
    appId: '1:765220729594:ios:ab126841c24ba241e64f43',
    messagingSenderId: '765220729594',
    projectId: 'gastos-aa516',
    storageBucket: 'gastos-aa516.appspot.com',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRjMQbeHWUOt1TQ3XsXjA4_k1j9HXo3Oc',
    appId: '1:765220729594:web:3d6d9629a32cf07ae64f43',
    messagingSenderId: '765220729594',
    projectId: 'gastos-aa516',
    authDomain: 'gastos-aa516.firebaseapp.com',
    storageBucket: 'gastos-aa516.appspot.com',
  );
}
